spring.application.name=Backend_TMDT

spring.datasource.url=jdbc:mysql://localhost:3306/tmdt
spring.datasource.username=root
spring.datasource.password=cuong1804sv@

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#Config Jwt
jwt.base64-secret=c2VjcmV0LWtleS1kZXB0cmFpLWJhY2tlbmQtdG1kdC1zcHJpbmdib290LWp3dC10b2tlbg==
jwt.access-token-validity-in-seconds=86400